### ISSUE TITLE
Update sugargame

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/across-and-down-activity#19]

**Comment by ayushnawal** [comment]
While running the activity, getting this import error `ModuleNotFoundError: No module named 'event' `  
and `except pygame.error, e`
i am fixing this issue.

**Comment by quozl** [comment]
I don't get that error, but I do get several others.

So I don't know how you got that error.  How are you running the activity?  I'm starting the activity from inside Sugar, or starting it using `sugar-activity3` in a Terminal inside Sugar.

Here are the errors I got;
```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/AcrossandDown.activity/sugargame/event.py", line 138, in _keyup_cb
    return self._keyevent(widget, event, pygame.KEYUP)
  File "/usr/share/sugar/activities/AcrossandDown.activity/sugargame/event.py", line 170, in _keyevent
    mod = self._keymods()
  File "/usr/share/sugar/activities/AcrossandDown.activity/sugargame/event.py", line 142, in _keymods
    for key_val, mod_val in self.mod_map.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
1575063377.659612 ERROR root: Error saving activity object to datastore
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 1277, in _prepare_close
    self.save()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 968, in save
    preview = self.get_preview()
  File "/usr/share/sugar/activities/AcrossandDown.activity/activity.py", line 65, in get_preview
    return self.game.canvas.get_preview()
  File "/usr/share/sugar/activities/AcrossandDown.activity/sugargame/canvas.py", line 82, in get_preview
    preview = f.read()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

  https://github.com/sugarlabs/across-and-down-activity/pull/17 was merged without testing by others, so there's work needed to finish porting to Python 3.
